# Generated by Django 3.1.2 on 2020-10-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='edition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
