# Generated by Django 3.1.2 on 2020-10-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20201014_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='edition',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
