# Generated by Django 3.1.2 on 2020-10-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20201014_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
