# Generated by Django 3.1.2 on 2020-10-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20201014_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='books',
            name='file',
            field=models.FileField(default='null', upload_to='bookFiles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='stream',
            field=models.CharField(default='Engineering', max_length=50),
            preserve_default=False,
        ),
    ]
