# Generated by Django 3.1.2 on 2020-10-17 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20201016_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='rating',
        ),
        migrations.AddField(
            model_name='books',
            name='upvote',
            field=models.ManyToManyField(related_name='rating_book', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(upload_to='bookFiles'),
        ),
        migrations.AlterField(
            model_name='books',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_owner_of_the_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
