# Generated by Django 3.1.2 on 2020-10-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20201017_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='upvote',
            new_name='like',
        ),
    ]
