# Generated by Django 3.1.2 on 2020-10-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20201018_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='user',
            new_name='uploaded_by',
        ),
    ]
