# Generated by Django 3.1.2 on 2020-10-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20201018_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
